- package-lock.json
- package.json
- vite.config.js
Fixes the necessity of iimporting css.
No issue to close
is only necessary to add a new vite plugin to add the css as an import
> fix: Remove the need to import react-chatbotify.css file

- src/components/ChatBotFooter/ChatBotFooter.tsx
- src/services/BotOptionsService.tsx
- src/types/Options.tsx
A new option called `buttons` is added to the footer options. It renders File Attachment and Emoji Picker by default. Custom buttons can be added in any order to footer by passing the components as an array to the `buttons` prop.
Closes #31 
> feat: allow custom buttons to be rendered in footer

- src/components/ChatBotHeader/ChatBotHeader.tsx
- src/services/BotOptionsService.tsx
- src/types/Options.tsx
Similar to the work done by @mushroomgenie on the footer component PR #33, this pull request introduces a new option called buttons to the header options. By default, the header now renders Notification, Audio, and Close buttons. Users can now customize the header buttons by passing their own components as an array to the buttons prop.
Closes #30 
> feat: allow custom buttons to be rendered in header

- src/components/ChatBotInput/ChatBotInput.tsx
- src/services/BotOptionsService.tsx
- src/types/Options.tsx
buttons is added to chatInput options to allow custom buttons. Can rearrange button position through array position. By default it will render voice and send button. 
Closes #35 
> feat: ChatInput component support custom buttons

- src/components/ChatHistoryButton/ChatHistoryButton.css
- src/components/ChatHistoryButton/ChatHistoryButton.tsx
Issue consisted of overflow issue in get history button
Closes #46 
- [ ✔️] Bug fix (non-breaking change which fixes an issue)
The approach includes preventing the text to wrap and then truncate with text-overflow to ellipses.
- [ ✔️] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [✔️ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ✔️] Relevant comments/docs have been added/updated (for bug fixes/features)
> Truncate history button

- package-lock.json
- package.json
- src/services/VoiceService.tsx
This replaces any type by its actual type. As well, it uses the right object, `window.SpeechRecognition` instead of `window.speechRecognition`.
[Docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API)
> fix: set speech recognition type and use the right object

- src/components/ChatBotButton/ChatBotButton.css
Added border-radius: inherit to allow custom icons to be cropped properly within the chat button’s box.
This update improves the appearance of the chat button icon by ensuring it does not overlap the previous layout.
Added border-radius: inherit to the toggle icon’s CSS.
> Fix Icon Cropping Issue in Chat Button

- src/components/ChatBotBody/ChatBotBody.tsx
- src/constants/internal/DefaultStyles.tsx
- src/types/Styles.ts
Added inline styles for "rcbDot" and  "rcbTypingIndicator" in ChatBotBody.tsx.
Closes issue #105
Added the styles in the "Styles.ts" and "DefaultStyles.tsx".
> chore: add inline style for typing indicator

- src/components/ChatBotInput/ChatBotInput.tsx
Add an isComposing state to the ChatInput component to prevent events from being triggered when the Enter key is pressed during IME conversion
Closes #109 
> feat: prevent sending in ChatInput while IME conversion is in progress

- src/components/ChatBotInput/ChatBotInput.tsx
- src/constants/RcbEvent.ts
- src/context/BotRefsContext.tsx
- src/hooks/internal/useTextAreaInternal.ts
- src/services/RcbEventService.tsx
- src/types/Settings.ts
- src/types/events/RcbTextareaChangeValue.ts
- types/global.d.ts
By adhering to the pattern with the emission of the other events, textarea-change-value event is emitted internally inside `useTextAreaInternal` at the setting of the value. All the checks inside the Input component was moved there, and if everything is passed the event is emitted.
Closes #111
Using the `inputRef` as the single source of truth, the addition of another ref to store the old value was added to store the old value.
> Feat: textarea value event emission

- .gitignore
- package.json
- src/components/ChatBot.tsx
- src/components/ChatBotContainer.tsx
- src/components/ChatBotInput/ChatBotInput.tsx
- src/components/ChatBotTooltip/ChatBotTooltip.tsx
- src/context/ChatBotProvider.tsx
- src/hooks/internal/useBotEffectInternal.tsx
- src/hooks/internal/useIsDesktop.ts
- src/services/VoiceService.tsx
- src/utils/displayChecker.ts
- ssr-test.js
Issue: for SSR projects (Next.js for eg.) importing anything outside types from the `react-chatbotify` package created an error related to global browser objects like `window` which were not defined at SSR time.
Changes:
- transformed `isDesktop` into a hook and replaced it everywhere
- moved two `useEffects` at the top level of the component, outside if statement (hook rules)
- moved SpeechRecognition initialization within a function call
- load Chatbot and ChatBotProvider only when DOM is ready
- added custom Node.js script to test SSR when importing ChatBot and ChatBotProvider
> fix: make library SSR compatible

- .eslintrc
- package-lock.json
- package.json
- src/hooks/internal/useMessagesInternal.ts
- src/hooks/internal/useSubmitInputInternal.ts
The `removeMessage` from `useMessages()` and `params` doesn't work because the `messages` are not updated within the `useCallback` wrapper of this function.
- added `eslint-plugin-react-hooks` devDependecy
- updated .eslintrc config to use the react-hooks and display warnings related to react hooks
- with the above configuration, the editor (VSCode) started to provide suggestions related to missing react hooks dependencies
- added the missing dependencies for `removeMessage` function
- added missing dependencies for other useCallback functions from the `useMessagesInternal.ts` and `useSubmitInputInternal.ts` files
- moved the `simulateStream` function before `injectMessage` since it was used before it was defined
Always add the …
> fix: removeMessage not working due to outdated messages state

- __tests__/hooks/useFirstInteractionInternal.test.ts
- src/context/BotStatesContext.tsx
Added unit tests for the hook useFirstInteractionInternal
Closes #128
> Add test for hook useFirstInteractionInternal

- __tests__/components/ChatHistoryButton/ChatHistoryButton.test.tsx
- src/components/ChatHistoryButton/ChatHistoryButton.tsx
Unit test for ChathHistoryButton
[#146 ]
Test for the following
- calls showchathistory when clicked, changes styles when hovered, and rendering the button correctly
> test: add unit test for chathistorybutton

- __tests__/components/ChatHistoryLineBreak/ChatHistoryLineBreak.test.tsx
- src/components/ChatHistoryLineBreak/ChatHistoryLineBreak.tsx
Added unit test for ChatHistoryLineBreak component.
Closes [#161](https://github.com/tjtanjin/react-chatbotify/issues/161)
Implement unit test using Jest and react testing library.
> test: add unit test for ChatHistoryLineBreak component

- __tests__/components/ChatBotFooter/ChatBotFooter.test.tsx
- __tests__/components/buttons/ChatBotButton.test.tsx
This PR adds unit tests for the `ChatBotButton` component, located in `__tests__/components/buttons/ChatBotButton.test.tsx`, to address issue #145. These tests verify that the component renders correctly, applies the proper CSS classes, and toggles visibility when clicked.
Closes #145
---
---
This PR introduces unit tests for the following cases:
- **Basic Render Test**: Ensures that the `ChatBotButton` renders correctly within the `TestChatBotProvider`.
- **CSS Class Application**: Verifies that the correct CSS class (`rcb-toggle-button`, `rcb-button-show`, `rcb-button-hide`) is applied based on the button's state.
- **Visibility Class Toggle**: Simulates a click event on the button to verify that the visibility toggles between `rcb-button-show` (visible) and `rcb-button-hide` (hidden). …
> Added unit test cases for ChatBotButton component

- __tests__/components/ChatHistoryButton/ChatHistoryButton.test.tsx
- __tests__/components/buttons/ChatBotButton.test.tsx
- Resolved warnings in ChatHistoryButton unit test
- Changed from space to tab indentation in ChatBotButton unit test
Related to these issues:
- ChatHistoryButton unit test - [#146](https://github.com/tjtanjin/react-chatbotify/issues/146)
- ChatBotButton unit test - [#145](https://github.com/tjtanjin/react-chatbotify/issues/145)
- `Warning: Removing a style property during rerender (borderColor) when a conflicting property is set (border) can lead to styling bugs.` fixed this warning by spliting border css to border and borderColor
- Change ChatBotButton unit test intentation from space to Tab
> fix: unit test warnings and code style lint issues

- __tests__/services/TransitionProcessor.test.ts
This PR adds unit tests for the processTransition function located in __tests__/services/BlockService/TransitionProcessor.test.ts, addressing issue #187.
Closes #187
- [x ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] Relevant comments/docs have been added/updated (for bug fixes/features)
> Added unit test cases for transition Processor

- __tests__/hooks/internal/useChatHistoryInternal.test.ts
- src/hooks/internal/useChatHistoryInternal.ts
- src/services/ChatHistoryService.tsx
`setTextAreaDisabled(settings.chatInput?.disabled)` is not called when the chatHistory is loaded.
Closes [#172](https://github.com/tjtanjin/react-chatbotify/issues/172)
- Added a useState variable in BotStatesContext.tsx to track chatHistory being loaded.
- Added a function call setIsChatHistoryLoaded(true) after setIsLoadingChatHistory(false).
- Added `useEffect()` to call `setTextAreaDisabled(false)` after chatHistory is done loading.
- Implement checking when chatHistory is done loading with a useState variable.
- Enable textArea when chatHistory is done loading.
- isChatHistoryLoaded stays remain true because there is no feature to hide the chat history.
- isChatHistoryLoaded can be set to false with hide chat history button (possible feature).
> fix: textArea is disabled after chatHistory is loaded

- __tests__/services/BlockService/OptionProcessor.test.tsx
> [Task] Add unit test cases for OptionProcessor #185

- __tests__/services/MessageProcessor.test.ts
Added unit test for MessageProcessor service.
Closes [#184](https://github.com/tjtanjin/react-chatbotify/issues/184)
Implemented unit test using Jest.
> test: add unit test for MessageProcessor service

- __tests__/hooks/internal/useFlowInternal.test.ts
This update introduces unit tests for the useFlowInternal hook, covering various scenarios such as retrieving initial context values, handling the flow state, and ensuring proper behavior of the restartFlow functionality. These tests aim to increase the reliability of the hook by verifying its interaction with contexts like MessagesContext, PathsContext, ToastsContext, BotRefsContext, and BotStatesContext.
Issue: [Task] Add unit test cases for useFlowInternal hook #129
Closes #129 
- [] Bug fix (non-breaking change which fixes an issue)
The proposed approach involves mocking the relevant contexts used within the useFlowInternal hook, then utilizing the @testing-library/react renderHook and act functions to simulate real usage scenarios.
> Add Unit tests for userFlowInternal Hook

- __tests__/utils/displayChecker.test.ts
Implemented unit tests for the isChatBotVisible function, ensuring it accurately determines whether a given HTMLDivElement is fully visible within the viewport.
Closes #196
Established a set of test scenarios, including edge cases, such as handling null and undefined inputs, and verifying conditions for when an element is fully or partially visible.
> test: add unit test cases for displayChecker utils

- __tests__/services/BlockService/IsSensitiveProcessor.test.ts
This PR adds unit tests for the `processIsSensitive` function within the `BlockService`. Additionally, it includes mocks for `params` and handles scenarios where `isSensitive` can be undefined, a boolean, a function, or a Promise.
Closes #183
This PR introduces unit tests for the `processIsSensitive` function, focusing on testing how the function handles different types for the isSensitive property (boolean, function, Promise, and undefined). The approach includes mocking params and ensuring that asynchronous and synchronous behaviors are properly tested. The function's logic is validated to ensure it correctly sets the `setTextAreaSensitiveMode` based on various return types from `isSensitive`.
> Test: Add unit test cases for IsSensitiveProcessor

- __tests__/utils/markupParser.test.ts
This pull request extends the unit test cases for the stripHtml function within the markupParser module. The new tests aim to improve test coverage by ensuring that the function handles various scenarios correctly.
Closes #(213)
This PR introduces additional unit tests for the stripHtml function within the markupParser module. The approach taken was to create tests that cover a range of common and edge cases, including:
- Input with plain text.
- HTML strings with single and nested tags.
- HTML strings with tags containing attributes.
- Handling of unclosed tags.
- Empty input cases.
> Test: Add unit test cases for stripHtml in markeupParser

- __tests__/hooks/internal/useSettingsInternal.test.ts
This PR introduces unit tests for the `useSettingsInternal` hook. These tests cover the hook's behavior, including returning settings, updating settings using helper functions, and handling edge cases like empty fields.
Closes #131 
The proposed approach involves writing unit tests for `useSettingsInternal`. The tests use `renderHook` to test the hook's output and behavior, mocking necessary context and utility functions to ensure the correct configuration flow when settings are updated.
> Test: Add unit tests for useSettingsInternal hook

- __tests__/hooks/internal/useMessagesInternal.test.ts
This PR introduces unit tests for the useMessagesInternal hook. These tests cover the hook's behavior, including returning messages, removing messages, using helper functions, and handling edge cases like empty fields.
Closes #126 
The proposed approach involves writing unit tests for useMessagesInternal. The tests use renderHook to test the hook's output and behavior, mocking necessary context and utility functions to ensure the correct configuration flow when settings are updated.
> test: add unit tests for useMessagesInternal hook

- __tests__/context/PathsContext.test.tsx
> chore: add test cases for PathsContext

- __tests__/context/ToastsContext.test.tsx
This Pull requests introduces unit testing for ToastsContext.
Closes #233 
The proposed approach involves writing unit tests for ToastContext. The tests use render from the React testing library to test the toast context and behavior.
> test: add unit tests for ToastsContext

- __tests__/context/SettingsContext.test.tsx
This Pull request introduces unit testing for ToastsContext.
Closes #231 
The proposed approach involves writing unit tests for SettingsContext. The tests use render from the React testing library to test the settings context and behavior.
> test: add unit tests for SettingsContext

- __tests__/hooks/internal/usePathsInternal.test.ts
Added unit test cases for usePathsInternal.ts
Closes #127 
> Successfully added unit test cases for usePathsInternal

- __tests__/utils/buttonBuilder.test.ts
> test: adding unit tests for buttonBuilder

- __tests__/components/ChatBotContainer/ChatBotContainer.test.tsx
This pull request introduces unit tests for the ChatBotContainer component, ensuring that the component correctly renders the header, input, and footer buttons based on the settings provided by the useSettingsContext.
Closes #222
The approach taken involves mocking the useSettingsContext hook to control the settings for the ChatBotContainer component. Three separate tests have been implemented to verify that the correct buttons are rendered based on the configuration of showHeader, showInputRow, and showFooter settings. Each test checks the presence or absence of the relevant buttons in the rendered output.
> Test: unit test cases for ChatBotContainer component

- __tests__/hooks/internal/useTextAreaInternal.test.ts
Closes #133 
Added unit tests for UseTextAreaInternal hook
- [✅] Test Cases
I was able to implement the test cases for the hook, however I was unable to generate accurate tests for toggle functions inside the hook, other than this everything seems to pass 
- [✅] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [✅] Testing has been done for the change(s) added (for bug fixes/features)
- [✅ ] Relevant comments/docs have been added/updated (for bug fixes/features)
> test: Added unit tests for UseTextAreaInternal hook (#133)

- __tests__/hooks/internal/useChatWindowInternal.test.ts
- src/hooks/internal/useChatWindowInternal.ts
Event listed [here](https://react-chatbotify.com/docs/api/events#rcbtogglechatwindowevent) has stale vale due to dependency array being empty but it needs to have access to `isChatWindowOpen` to work properly.
Also I've updated the test case so it covers actual toggling of chat window (it is failing  without `isChatWindowOpen` passed as dependency)
Updating dependency array for `useCallback` hook
> fix: add missing isChatWindowOpen dependency

- __tests__/components/buttons/FileAttachmentbutton.test.tsx
- src/components/Buttons/FileAttachmentButton/FileAttachmentButton.tsx
Added unit test for FileAttachmentButton component
Closes #141 
The proposed approach focuses on validating the behavior and rendering of the `FileAttachmentButton` component, ensuring that it works as expected based on its context and props. This includes:
1. **Rendering Verification**:
- Confirming that the button and input elements are correctly rendered with the expected attributes, such as `aria-label`, `type`, `accept`, and `multiple`.
2. **State-Dependent Icon Rendering**:
- Testing that the button’s enabled and disabled states render the correct classes and icons based on the `blockAllowsAttachment` context value.
3. **Preventing Invalid Actions**:
- Verifying that the `handleUpload` function does not proceed when certain conditions are unmet, …
> Added FileAttachmentButton test

- __tests__/components/ChatBotBody/UserCheckboxes.test.tsx
Fixes: #151
Added tests to make sure the checkboxes are working as expected.
Please let me know if there are any changes to be made.
> Add tests for UserCheckboxes component

- __tests__/hooks/internal/useTextAreaInternal.test.ts
- src/hooks/internal/useTextAreaInternal.ts
- src/hooks/useTextArea.ts
This PR introduces the `unFocusTextArea` functionality in the `useTextAreaInternal` hook, which allows programmatic removal of focus from the text area. This complements the existing `focusTextArea` method and provides additional control over the text area's behavior.
NA
The unFocusTextArea method was added as a useCallback function within the useTextAreaInternal hook. It leverages the blur method on the inputRef to remove focus from the text area. Additionally, a new test case was created to verify this behavior, ensuring it works as intended without impacting existing functionality.
> Added unFocusTextArea to manage text area blur functionality

- __tests__/__mocks__/fileMock.ts
- __tests__/components/buttons/VoiceButton.test.tsx
- src/components/Buttons/VoiceButton/VoiceButton.tsx
Add unit tests for Voice Button component
Closes #137 
An approach similar to the implementation of unit tests for Notification Button component is followed.
- [n/a] Testing has been done for the change(s) added (for bug fixes/features)
- [n/a] Relevant comments/docs have been added/updated (for bug fixes/features)
> Add unit tests for Voice Button component

- __tests__/components/ChatBot.test.tsx
- __tests__/components/ChatBotBody/ChatMessagePrompt.test.tsx
This change includes the setup of mocks for dependencies used in the [ChatBot](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) component tests. It mocks the idGenerator, ChatBotContext, ChatBotLoader, and ChatBotContainer to isolate the component being tested and ensure that the tests are not affected by the actual implementations of these dependencies.
Closes #221 
UUID Generation: Mocked idGenerator to return a consistent UUID ("mocked-uuid") using jest.fn().
ChatBot Context: Mocked useChatBotContext hook and ChatBotProvider component to provide controlled context values.
Component Mocks: Mocked …
> [Test] [Issue- 221] :  Add unit test for ChatBot

- __tests__/hooks/internal/useFlowInternal.test.ts
- __tests__/services/ChatHistoryService.test.ts
- src/hooks/internal/useFlowInternal.ts
- src/hooks/internal/useMessagesInternal.ts
- src/services/ChatHistoryService.tsx
Changed saveChatHistory by assigning the latest state to ChatHistoryService it's historyMessages.
Closes https://github.com/tjtanjin/react-chatbotify/issues/282
- Fix the bug
-Change / Add tests
> ISSUE-282 keep history messages in sync with storage

- __tests__/hooks/internal/useMessagesInternal.test.ts
- src/hooks/internal/useMessagesInternal.ts
This PR adds support for a callback pattern in the replaceMessages function, similar to React's setState. This allows users to update messages based on the current state without causing infinite re-render loops when used inside useEffect.
Closes #329
The replaceMessages function now accepts either:
1. An array of messages (existing behavior - maintains backward compatibility)
2. A callback function that receives the current messages and returns new messages
- [no] Relevant comments/docs have been added/updated (for bug fixes/features)
- The docs don't seem to be in this repo? 👀
> Support callback function in replaceMessages

- src/services/AudioService.ts
This PR fixes a SonarQube issue (TypeScript:S2201 – "Return values should not be ignored") 
in the speech synthesis voice selection logic.
- Replaced the use of `Array.find` with proper handling of its return value
- Ensured the matched voice is assigned to the utterance before calling `speak`
- Improved code readability and compliance with static analysis rules
SonarQube detected that the return value of `find` was being ignored, which could 
lead to confusion or potential bugs. This fix ensures the return value is properly 
utilized and eliminates the warning.
- Verified that voices are still correctly matched by name
- Confirmed that speech synthesis works as expected after the change
The current implementation uses Array.find only for its side …
> Fix: prevent ignoring return value in speech synthesis voice selection

- .gitignore
- __tests__/services/VoiceService.test.ts
Added unit tests for `VoiceService` covering:
- starting/stopping speech recognition and MediaRecorder
- syncing voice input with chat
- handling `onresult`, `onend`, and `ondataavailable` events
- timeout, auto-send, and edge cases (missing APIs, voice disabled)
Improves reliability and prevents regressions in future changes.
> Unit test for VoiceService
