- .husky/pre-commit
- package-lock.json
- package.json
Added husky, a pre commit hook to check for lint errors and fixing them.
Closes #24 
Installed husky as a dev dependency. Added `npm run lint` command to the pre commit hook.
> [Task] Adding pre commit hook to check for lint errors and fixing them

- package-lock.json
- package.json
- vite.config.js
This setups eslint locally so devs are aware of what are against the eslint's rules.
> lint: Setup eslint locally

- src/components/ChatBotBody/ChatBotBody.tsx
- src/components/ChatBotBody/ChatMessagePrompt/ChatMessagePrompt.tsx
- src/components/ChatBotButton/ChatBotButton.tsx
- src/components/ChatBotHeader/ChatBotHeader.tsx
- src/components/ChatBotInput/ChatBotInput.tsx
- src/components/ChatBotInput/SendButton/SendButton.tsx
- src/components/ChatBotTooltip/ChatBotTooltip.tsx
- src/components/ChatHistoryButton/ChatHistoryButton.tsx
- src/components/LoadingSpinner/LoadingSpinner.tsx
- src/components/UserCheckboxes/UserCheckboxes.tsx
- src/components/UserOptions/UserOptions.tsx
- src/types/Options.tsx
This is the enhancement to set the right type for style.
> fix: use css properties type for style

- src/components/ChatBotFooter/EmojiPicker/EmojiPicker.tsx
- src/components/ChatBotInput/SendButton/SendButton.tsx
- src/components/ChatBotTooltip/ChatBotTooltip.tsx
- src/services/BotOptionsService.tsx
This removes unused logic and replaces any type by object type
It removes unused logic and replaces type
> end: replace any type by options type

- src/App.tsx
- src/components/ChatBotContainer.tsx
- src/components/ChatBotFooter/ChatBotFooter.tsx
- src/components/ChatBotFooter/FileAttachmentButton/FileAttachmentButton.tsx
- src/components/ChatBotInput/ChatBotInput.tsx
- src/components/UserCheckboxes/UserCheckboxes.tsx
- src/components/UserOptions/UserOptions.tsx
- src/context/PathsContext.tsx
- src/services/BlockService/BlockService.tsx
- src/services/BlockService/CheckboxProcessor.tsx
- src/services/BlockService/OptionProcessor.tsx
- src/services/BlockService/TransitionProcessor.tsx
- src/services/Utils.tsx
- src/types/Flow.ts
- src/types/Flow.tsx
- src/types/Params.tsx
This PR replaces generic string types by the existing type, Flow.
It simply replaces string type by the Flow type.
> enh: refactor flow type

- package-lock.json
- package.json
- test/RunTests.js
- test/config.js
This feature adds the 3 missing tests as specified in the issue bellow, scecifically:
- User cannot type above character limit if it is set (characterLimit)
- When new messages are received, the new message popup is shown (showMessagePrompt)
- When user clicks on new message prompt, it automatically scrolls down to the latest message (autoJumpToBottom)
!Also updates the selenium-webdriver from ^4.19.0 to ^4.20.0 in package.json
Closes #29
> Add missing tests

- src/services/ChatHistoryService.tsx
This removes type assertions applied to the color property.
It simply removes type assertion.
> enh: clean up type assertion to color

- src/services/BlockService/PathProcessor.tsx
This removes @ts-ignore
Added a new variable with type-guard so we know that the variable's type is `string`
> enh: fix @ts-ignore

- cypress.config.ts
- cypress/e2e/tests.cy.ts
- cypress/support/e2e.ts
- cypress/support/functions.ts
- src/services/ThemeService.tsx
- tsconfig.json
- types/cypress.d.ts
> test: add tests for theme caching

- __tests__/hooks/userBotIdInternal.test.ts
added test for hook useBotIdInternal
Closes #132
- [x ] Add unit test
Followed other unit tests structure and make the jest tests to test the changes
- [ X] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ X] Testing has been done for the change(s) added (for bug fixes/features)
- [ X] Relevant comments/docs have been added/updated (for bug fixes/features)
> test: added test for hook useBotIdInternal  #132

- __tests__/components/NotificationButton.test.tsx
Add unit test for NotificationButton component
Closes #([issue](https://github.com/tjtanjin/react-chatbotify/issues/138))
> test: add unit test for NotificationButton component

- cypress/e2e/tests.cy.ts
- src/App.tsx
Images:
1.  sensitive text 
2. Markup language
> test: Adding Cypress integration testcase for Sensitive input

- __tests__/components/ChatBotBody/ToastPrompt.test.tsx
Added unit test for ToastPrompt #150
Closes #150 
- [] Documentation update (changes to docs/code comments)
Implement unit test using Jest and react testing library
- [X ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
> test: added unit test for ToastPrompt #150

- __tests__/components/ChatBotBody/UserOptions.test.tsx
> Closes issue #152 (unit test for UserOptions component)

- __tests__/components/buttons/CloseChatButton.test.tsx
Added test for CloseChatButton
Added unit test for CloseChatButton using Jest
Closes #139 
- [ X] Unit Test 
Followed other unit tests structure and make the jest tests to test the changes
> test: added test for CloseChatButton #139

- __tests__/components/ChatBotBody/MediaDisplay.test.tsx
- src/components/ChatBotBody/MediaDisplay/MediaDisplay.tsx
Added unit test for the MediaDisplay component
Tested for image rendering correctly, video rendering correctly if type is video and also audio if type is audio
> test:added mediaDisplay Unit test

- __tests__/components/buttons/SendButton.test.tsx
Added unit test for SendButton component.
Closes #([142](https://github.com/tjtanjin/react-chatbotify/issues/142))
Implement unit test using Jest and react testing library.
> test: add unit test for SendButton component

- __tests__/__mocks__/fileMock.ts
- __tests__/components/ChatBotHeader/ChatBotHeader.test.tsx
Added unit test for ChatBotHeader component
Closes [#157](https://github.com/tjtanjin/react-chatbotify/issues/157)
Implement unit test using Jest and react testing library.
> test: add unit test for ChatBotHeader component

- __tests__/components/ChatBotFooter/ChatBotFooter.test.tsx
- src/components/ChatBotFooter/ChatBotFooter.tsx
Added the Unit Test for the Chat Bot Footer with simple tests on buttons, icons, and text.
Closes #158 
Added the unit test for Footer component with jest and react.
> test: Add the unit test for chatbot footer component

- __tests__/services/ComponentProcessor.test.tsx
Added unit test for component processor service.
Closes [#176](https://github.com/tjtanjin/react-chatbotify/issues/176)
Implemented unit test using Jest.
> test: add unit test for component processor service

- __tests__/__mocks__/fileMock.ts
- __tests__/components/buttons/EmojiButton.test.tsx
Added unit test for EmojiButton component.
Closes [#140](https://github.com/tjtanjin/react-chatbotify/issues/140)
Implement unit test using Jest and react testing library.
> test: add unit test for EmojiButton component

- __tests__/services/FunctionProcessor.test.ts
Added unit tests for the `processFunction` in `BlockService/FunctionProcessor` to ensure correct functionality when handling blocks with and without functions, handling promises, and managing errors.
Closes # (issue)
Implemented unit tests using Jest to verify the behavior of the `processFunction`. The tests cover:
- Returning `undefined` when the block has no function.
- Returning the result of the function when it is not a promise.
- Returning the resolved value of the function when it is a promise.
- Handling function throwing an error.
- Handling function returning a rejected promise.
Screenshot - 
- [] I have updated the documentation accordingly.
> Wrote test cases for FunctionProcessor

- __tests__/services/BlockService/CheckboxProcessor.test.tsx
> [Task] Add unit test cases for CheckboxProcessor #175

- __tests__/utils/idGenerator.test.ts
> Add test cases for idGenerator utils

- __tests__/utils/configParser.test.ts
> [Task] Add unit test cases for configParser utils #195

- __tests__/services/ThemeService.test.ts
- src/services/ThemeService.ts
- viteconfig.ts
This PR adds unit tests for ThemeService and includes a configuration update to address issues with Jest not properly handling Vite environment variables. The configuration change allows Jest to mock Vite environment variables, resolving issues that prevented the tests from running.
Closes #(166)
Adding unit tests for ThemeService to ensure its functionality is thoroughly tested. Creating a separate configuration module (viteconfig.ts) for Vite environment variables, allowing them to be mocked in Jest tests, overcoming compatibility issues between Jest and import.meta in Vite.
> Test: Add unit test cases for ThemeService

- __tests__/utils/mediaFileParser.test.ts
> Add test cases for mediaFileParser utils

- __tests__/context/MessagesContext.test.tsx
> Add test cases for message context

- __tests__/hooks/internal/useIsDesktopInternal.test.ts
> test: adds unit tests for the hook useIsDesktopInternal

- __tests__/context/ChatBotContext.test.tsx
Added relevant unit test cases (4) for ChatBotContext.tsx.
Closes #228 
The goal of these unit test cases is to ensure that they validate the intended functionality of ChatBotContext, especially in scenarios involving state changes and asynchronous configuration loading.
> test: add unit test cases for ChatBotContext

- __tests__/hooks/internal/useStylesInternal.test.ts
Adds test for useStylesInternal hook
Closes #225 
I used existing tests as an example.
> Add unit test cases for useStylesInternal hook

- __tests__/services/BlockService/PathProcessor.test.ts
Added Unit test for PathProcessor Block service
Closes #186 
The goal is to test all the possible logical flows of `PathProcessor.test.ts` service and using `jest.mock` to mock functionality where applicable.
> Test: Added unit test cases for PathProcessor

- __tests__/services/ChatHistoryService.test.ts
Update unit test for ChatHistoryService
Closes #268
The proposed approach adds a new parameter `storageType: "SESSION_STORAGE"` to most of the unit tests inside `ChatHistoryService.test.ts` file to cover both storage types without duplicating the test blocks.
> Update ChatHistoryService unit tests to cover a new storageType

- src/constants/internal/DefaultSettings.tsx
This PR updates all window.open calls in DefaultSettings to include the "_blank", "noopener,noreferrer" parameters.
- Prevents reverse tabnabbing by disabling window.opener access.
- Ensures compliance with TypeScript:S5148 Sonar rule.
- Improves overall security when opening external links.
The approach taken was to update all usages of window.open to explicitly include the parameters "_blank", "noopener,noreferrer".
- This prevents the newly opened window from accessing the opener through window.opener, addressing the security-sensitive issue highlighted in TypeScript:S5148.
- The change is minimal and localized, ensuring no impact on existing functionality while eliminating the reverse tabnabbing risk.
> Fix: window.open security issue by adding noopener,noreferrer (S5148)
